version: "3"

services:
  rif-relay:
    build:
      context: .
    # entrypoint: sh -c 'node dist/commands/Start.js --config server-config.testnet.json'
    # entrypoint: sh -c 'node dist/commands/Start.js --config server-config.json'
    entrypoint: sh -c 'node dist/commands/Start.js --config server-config.docker.json'
    ports:
      - "8090:8090"
    volumes:
      - "./environment:/srv/app/environment"
    networks:
      - rif-relay

networks:
  rif-relay:
    driver: bridge
